version: '3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - ./users/migrations:/migrations/users
      - ./rooms/migrations:/migrations/rooms
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=ghbdtn11
      - POSTGRES_USER=admin
      - POSTGRES_DB=bookroom
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  users:
    build: ./users
    ports:
      - '4022:4022'
      - '9229:9229'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  rooms:
    build: ./rooms
    ports:
      - '5050:5050'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  dbdata: